"""empty message

Revision ID: 96390e5136c6
Revises: 7e990b3e910a
Create Date: 2022-08-04 23:21:41.210253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96390e5136c6'
down_revision = '7e990b3e910a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('Venue', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###
